language: php

dist: xenial

php:
- 7.0

env:
- BD=pgsql

before_install:
- sudo apt-get update -q

before_script: true

script: 
- phpunit test.php


notifications:
  email:
    - rsabando@espol.edu.ec
    
irc: "irc.freenode.org#yourfavouriteroomfortravis"
